### ISSUE TITLE
[Question] multiple data to index

### ISSUE THREAD

**Issue by cigoic** [dylanjcastillo/semantic-search-elasticsearch-openai-langchain#1]
Hi,

Thanks for a great tutor related to ElasticSearch and OpenAI.

I am wondering how I format my data in order to feed into ElasticSearch for indexing?

HTML, CSV, TXT? I saw you use Paths.book to load the data.

If I have multiple source data files, how do I name, arrange them in folder(s) and index them?  

Thanks.

**Comment by dylanjcastillo** [comment]
Hi @cigoic,

You can use any of those formats, you just have to use a [loader](https://python.langchain.com/en/latest/modules/indexes/document_loaders.html) that works for those. If you have multiple files, you can simply use a loop to split the files and index them.
